menuBubbles = {}

function drawMainMenu()
  love.graphics.print("High Score = " .. highScore, 0, 0)
  love.graphics.draw(menuBackground, 0, 0)
  love.graphics.setFont(largeFont)
  love.graphics.setColor(1, 1, 1)
  love.graphics.draw(menuTitle, love.graphics.getWidth()/5.5, love.graphics.getHeight()/4)
  love.graphics.setColor(1, 1, 1, .5)
  love.graphics.draw(bubblePic, 200, love.graphics.getHeight()/2.5, 0, 1.75)
  love.graphics.setColor(0, 0, 0)
  love.graphics.setFont(myFont)
  love.graphics.print("Family", 233, love.graphics.getHeight()/2.5 + 65)
  love.graphics.setColor(1, 1, 1, .5)
  love.graphics.draw(bubblePic, 400, love.graphics.getHeight()/2.5, 0, 1.75)
  love.graphics.setColor(0, 0, 0)
  love.graphics.print("Numbers", 233+170, love.graphics.getHeight()/2.5 + 65)
  love.graphics.setColor(1, 1, 1, .5)
  love.graphics.draw(bubblePic, 600, love.graphics.getHeight()/2.5, 0, 1.75)
  love.graphics.setColor(0, 0, 0)
  love.graphics.print("Colors", 600 +30, love.graphics.getHeight()/2.5 + 65)
  love.graphics.setColor(1, 1, 1, .5)
  love.graphics.draw(bubblePic, 800, love.graphics.getHeight()/2.5, 0, 1.75)
  love.graphics.setColor(0, 0, 0)
  love.graphics.print("Letters", 800 +30, love.graphics.getHeight()/2.5 + 65)
  love.graphics.setColor(1, 1, 1, .5)
  love.graphics.draw(bubblePic, 1000, love.graphics.getHeight()/2.5, 0, 1.75)
  love.graphics.setColor(0, 0, 0)
  love.graphics.print("Shapes", 1000 +30, love.graphics.getHeight()/2.5 + 65)
  love.graphics.setColor(1, 1, 1, .5)
end
